apiVersion: v2
appVersion: 0.1.0
description: A Helm chart for Kubernetes
name: remote-payments-developer-docs
type: application
version: 0.1.0
dependencies:
  - name: common
    version: 0.1.0
    repository: https://storage.googleapis.com/firefly-helm-charts