container:
  lifecycle:
    preStop:
      exec:
        command:
          - /bin/sleep
          - '20'
  readinessProbe:
    httpGet:
      path: '/'
      port: http

podDisruptionBudget:
  enabled: true
  minAvailable: 2

routeTable:
  prefix: /