container:
  lifecycle:
    preStop:
      exec:
        command:
          - /bin/sleep
          - '20'
  readinessProbe:
    httpGet:
      path: '/'
      port: http

  resources: # Only pass if you want to reserve resources for container
    limits:
      cpu: 750m
      memory: 3Gi
    requests:
      cpu: 100m
      memory: 250Mi

podDisruptionBudget:
  enabled: true
  minAvailable: 2

routeTable:
  prefix: /