/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  RemotePaymentsSidebar: [
   'remote-payments/introduction',
   'remote-payments/getting-started',
    {
      type: 'category',
      label: 'Accept payments',
      link: {
        type: 'doc', id: 'remote-payments/accept-payments/accept-payments'
      },
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Checkout page',
          link: {
            type: 'doc', id: 'remote-payments/accept-payments/checkout-page/checkout-page'
          },
          items: [
            'remote-payments/accept-payments/checkout-page/step-by-step-guide',
            'remote-payments/accept-payments/checkout-page/configuration',
          ],
        },
        {
          type: 'category',
          label: 'Payment links',
          link: {
            type: 'doc', id: 'remote-payments/accept-payments/payment-links/payment-links'
          },
          items: [
            'remote-payments/accept-payments/payment-links/step-by-step-guide',
          ],
        },
        {
          type: 'category',
          label: 'Components',
          link: {
            type: 'doc', id: 'remote-payments/accept-payments/components/components'
          },
          items: [
            'remote-payments/accept-payments/components/card',
            'remote-payments/accept-payments/components/wallet',
            'remote-payments/accept-payments/components/configuration',
          ],
        },
        'remote-payments/accept-payments/api-only',
      ],
    },
    {
      type: 'category',
      label: 'Manage payments',
      link: {
        type: 'doc', id: 'remote-payments/manage-payments/manage-payments'
      },
      collapsed: true,
      items: [
        'remote-payments/manage-payments/capture',
        'remote-payments/manage-payments/change-amount',
        'remote-payments/manage-payments/send-receipt',
        {
          type: 'category',
          label: 'Cancellation payments',
          link: {
            type: 'doc', id: 'remote-payments/manage-payments/cancellation-payments/cancellation-payments'
          },
          items: [
            'remote-payments/manage-payments/cancellation-payments/cancel',
            'remote-payments/manage-payments/cancellation-payments/reversal',
            'remote-payments/manage-payments/cancellation-payments/refund',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Plugins',
      link: {
        type: 'doc', id: 'remote-payments/plugins/plugins'
      },
      collapsed: true,
      items: [
        'remote-payments/plugins/magento',
        'remote-payments/plugins/opencart',
        'remote-payments/plugins/prestashop',
        'remote-payments/plugins/woocommerce',
      ],
    },
    {
      type: 'category',
      label: 'Development resources',
      link: {
        type: 'doc', id: 'remote-payments/development-resources/development-resources'
      },
      collapsed: true,
      items: [
        'remote-payments/development-resources/versioning-overview',
        'remote-payments/development-resources/data-types',
        'remote-payments/development-resources/webhooks',
        'remote-payments/development-resources/testing',
        'remote-payments/development-resources/sdk'
        
      ],
    },
  ],
  Tables: [
    {
      type: 'autogenerated',
      dirName: 'tables',
    },
  ],
};



module.exports = sidebars;
