get:
  summary: 'List all receipt configurations'
  description: 
    $ref: ../../prose/endpoints/searchReceiptConfiguration.md
  tags:
    - Receipts
  parameters:
    - name: version
      in: header
      required: true
      schema: 
        type: string 
        format: date
      example: '2022-04-07'
      description:
        $ref: ../../prose/parameters/version.md
  responses:
    '200':
      description: Success
      content:
        application/json:
          schema:
            $ref: ../components/schemas/ReceiptConfigurationResponse.yaml
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../components/schemas/ProblemDetails.yaml
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: ../components/schemas/ProblemDetails.yaml
  security: 
    - BasicAuth: []
